name: Build SuperCollider Plugin (multi-platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - uses: actions/checkout@v4

      # --- Dependencies ---
      - name: Install minimal dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config
      - name: Install minimal dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake pkg-config

      # --- Paths ---
      - name: Set build directories
        id: paths
        shell: bash
        run: |
          echo "sc-dir=${{ github.workspace }}/SuperCollider" >> "$GITHUB_OUTPUT"
          echo "plugin-build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "install-dir=${{ github.workspace }}/install" >> "$GITHUB_OUTPUT"

      # --- Clone SuperCollider headers ---
      - name: Clone SuperCollider
        run: git clone --depth=1 https://github.com/supercollider/supercollider.git ${{ steps.paths.outputs.sc-dir }}

      - name: Initialize submodules
        run: |
          cd ${{ steps.paths.outputs.sc-dir }}
          git submodule update --init --recursive

      - name: Configure plugin with CMake
        shell: bash
        run: |
          # Normalize paths to use forward slashes for CMake (Windows-safe)
          SRC_DIR=$(echo "${{ github.workspace }}" | sed 's|\\|/|g')
          BUILD_DIR=$(echo "${{ steps.paths.outputs.plugin-build-dir }}" | sed 's|\\|/|g')
          SC_DIR=$(echo "${{ steps.paths.outputs.sc-dir }}" | sed 's|\\|/|g')
          INSTALL_DIR=$(echo "${{ steps.paths.outputs.install-dir }}" | sed 's|\\|/|g')

          echo "Source directory: $SRC_DIR"
          echo "Build directory: $BUILD_DIR"
          echo "SuperCollider headers: $SC_DIR"
          echo "Install directory: $INSTALL_DIR"

          cmake -B "$BUILD_DIR" \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DSC_PATH="$SC_DIR" \
                -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
                -S "$SRC_DIR"


      # --- Build ---
      - name: Build plugin
        run: cmake --build ${{ steps.paths.outputs.plugin-build-dir }} --config ${{ matrix.build_type }}

      # --- Install ---
      - name: Install plugin (reproduce CMake install layout)
        run: cmake --install ${{ steps.paths.outputs.plugin-build-dir }} --config ${{ matrix.build_type }}

      # --- Verify structure ---
      - name: List installed structure
        shell: bash
        run: |
          echo "Installed plugin package structure:"
          ls -Rlah ${{ steps.paths.outputs.install-dir }}

      # --- Upload the complete install folder ---
      - name: Upload built plugin package
        uses: actions/upload-artifact@v4
        with:
          name: PHMSC-${{ matrix.os }}
          path: ${{ steps.paths.outputs.install-dir }}
