name: Build SuperCollider Plugin (multi-platform)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl

    steps:
      - uses: actions/checkout@v4

      # --- Dependencies ---
      - name: Install minimal dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config
      - name: Install minimal dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake pkg-config

      # --- Set paths ---
      - name: Set build directories
        id: paths
        shell: bash
        run: |
          echo "sc-dir=${{ github.workspace }}/SuperCollider" >> "$GITHUB_OUTPUT"
          echo "plugin-build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          echo "install-dir=${{ github.workspace }}/install" >> "$GITHUB_OUTPUT"

      # --- Clone SuperCollider headers ---
      - name: Clone SuperCollider
        run: git clone --depth=1 https://github.com/supercollider/supercollider.git ${{ steps.paths.outputs.sc-dir }}

      - name: Initialize submodules
        run: |
          cd "${{ steps.paths.outputs.sc-dir }}"
          git submodule update --init --recursive

      # --- Configure ---
      - name: Configure plugin with CMake
        shell: bash
        run: |
          SRC_DIR=$(echo "${{ github.workspace }}" | sed 's|\\|/|g')
          BUILD_DIR=$(echo "${{ steps.paths.outputs.plugin-build-dir }}" | sed 's|\\|/|g')
          SC_DIR=$(echo "${{ steps.paths.outputs.sc-dir }}" | sed 's|\\|/|g')
          INSTALL_DIR=$(echo "${{ steps.paths.outputs.install-dir }}" | sed 's|\\|/|g')

          echo "Source directory: $SRC_DIR"
          echo "Build directory: $BUILD_DIR"
          echo "SuperCollider headers: $SC_DIR"
          echo "Install directory: $INSTALL_DIR"

          cmake -B "$BUILD_DIR" \
                -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
                -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
                -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                -DSC_PATH="$SC_DIR" \
                -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
                -S "$SRC_DIR"

      # --- Build ---
      - name: Build plugin
        shell: bash
        run: |
          BUILD_DIR=$(echo "${{ steps.paths.outputs.plugin-build-dir }}" | sed 's|\\|/|g')
          cmake --build "$BUILD_DIR" --config ${{ matrix.build_type }}

      # --- Install ---
      - name: Install plugin
        shell: bash
        run: |
          BUILD_DIR=$(echo "${{ steps.paths.outputs.plugin-build-dir }}" | sed 's|\\|/|g')
          cmake --install "$BUILD_DIR" --config ${{ matrix.build_type }}

      # --- Flatten nested plugin folders ---
      - name: Flatten nested plugin directories
        shell: bash
        run: |
          INSTALL_DIR=$(echo "${{ steps.paths.outputs.install-dir }}" | sed 's|\\|/|g')
          echo "Flattening structure in: $INSTALL_DIR"
          cd "$INSTALL_DIR/plugins" || exit 0
          for d in */*/; do
            parent=$(dirname "$d")
            child=$(basename "$d")
            if [ "$parent" == "$child" ]; then
              echo "Flattening $d -> $parent/"
              mv "$d"* "$parent"/ 2>/dev/null || true
              rm -rf "$d"
            fi
          done

      # --- Verify ---
      - name: List installed plugin structure
        shell: bash
        run: |
          INSTALL_DIR=$(echo "${{ steps.paths.outputs.install-dir }}" | sed 's|\\|/|g')
          echo "Installed plugin package structure:"
          ls -Rlah "$INSTALL_DIR" || true

      # --- Upload artifact ---
      - name: Upload built plugin package
        uses: actions/upload-artifact@v4
        with:
          name: PHMSC-${{ matrix.os }}
          path: ${{ steps.paths.outputs.install-dir }}
